@startuml
class ApplicationUser {
    + ApplicationUser()
    + ApplicationUser(id:string, name:string, surname:string, userName:string)
    + Age : Int32 <<get>> <<set>>
    + DNI : String <<get>> <<set>>
    + Name : String <<get>> <<set>>
    + Sex : String <<get>> <<set>>
    + Surname : String <<get>> <<set>>
}
IdentityUser <|-- ApplicationUser
@enduml
