@startuml
class ClaseDeportiva {
    + ClasesInscritas : IList<ClaseInscrita> <<get>> <<set>>
    + Descripcion : String <<get>> <<set>>
    + FechaHora : DateTime <<get>> <<set>>
    + Id : Int32 <<get>> <<set>>
    + Lugar : String? <<get>> <<set>>
    + Monitor : String <<get>> <<set>>
    + Nivel : String <<get>> <<set>>
    + PlazasDisponibles : Int32 <<get>> <<set>>
    + PrecioUnitario : Decimal <<get>> <<set>>
    + tipoDeporte : TipoDeporte <<get>> <<set>>
    + TipoDeporteId : Int32 <<get>> <<set>>
    + ClaseDeportiva()
}
@enduml
