@startuml
class ClaseInscrita {
    + ClaseDeportiva : ClaseDeportiva <<get>> <<set>>
    + ClaseDeportivaId : Int32 <<get>> <<set>>
    + Id : Int32 <<get>> <<set>>
    + Inscripcion : Inscripcion <<get>> <<set>>
    + InscripcionId : Int32 <<get>> <<set>>
    + Observaciones : String? <<get>> <<set>>
    + PlazasReservadas : Int32 <<get>> <<set>>
    + Precio : Decimal <<get>> <<set>>
    + ClaseInscrita()
}
@enduml
