@startuml
!include .\\ApplicationUser.puml
!include .\\MaterialAlquilado.puml
!include .\\Material.puml
!include .\\Alquiler.puml
!include .\\ApplicationUser.puml
!include .\\ClaseDeportiva.puml
!include .\\Inscripcion.puml
!include .\\ClaseInscrita.puml
!include .\\PistaReservada.puml
@enduml
