@startuml
enum MetodoPago {
    Bizum,
    Efectivo,
    Tarjeta,
    Transferencia,
    Metalico,
}
class Inscripcion {
    + Inscripcion()
}
class "IList`1"<T> {
}
Inscripcion --> "ClasesInscritas<ClaseInscrita>" "IList`1"
Inscripcion --> "Cliente" ApplicationUser
Inscripcion --> "DatosPago" String
Inscripcion --> "FechaInscripcion" DateTime
Inscripcion --> "Id" Int32
Inscripcion --> "MetodoPago" MetodoPago
Inscripcion --> "PrecioTotal" Decimal
Inscripcion --> "ApellidosUsuario" String
Inscripcion --> "DNI" String
Inscripcion --> "NombreUsuario" String
Inscripcion --> "Telefono" String
Inscripcion --> "CompeticionInscripciones<CompeticionInscripcion>" "IList`1"
@enduml
