@startuml
enum MetodoPago {
    Bizum,
    Efectivo,
    Tarjeta,
    Transferencia,
    Metalico,
}
class Inscripcion {
    + ClasesInscritas : IList<ClaseInscrita> <<get>> <<set>>
    + CompeticionInscripciones : IList<CompeticionInscripcion> <<get>> <<set>>
    + Cliente : ApplicationUser <<get>> <<set>>
    + DatosPago : String <<get>> <<set>>
    + FechaInscripcion : DateTime <<get>> <<set>>
    + Id : Int32 <<get>> <<set>>
    + MetodoPago : MetodoPago <<get>> <<set>>
    + PrecioTotal : Decimal <<get>> <<set>>
    + Inscripcion()
}
@enduml
