@startuml
class Material {
    + Material()
    + Material(id:string, nombrematerial:string, cantidad:int, preciomaterial:decimal)
    + Cantidad : int <<get>> <<set>>
    + IdMaterial : string <<get>> <<set>>
    + NombreMaterial : string <<get>> <<set>>
    + PrecioMaterial : decimal <<get>> <<set>>
    + IdTipoMaterial : string <<get>> <<set>>
    + IdTipoDeporte : string <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
class "IList`1"<T> {
}
Material o-> "MaterialesAlquileres<MaterialAlquilado>" "IList`1"
Material --> "TipoMaterial" TipoMaterial
Material --> "TipoDeporte" TipoDeporte
@enduml
