@startuml
class Pista {
    + Pista()
    + IdPista : int <<get>> <<set>>
    + NombrePista : string <<get>> <<set>>
    + NPersonas : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + IdTipoDeporte : int <<get>> <<set>>
    + TipoDeporte : TipoDeporte <<get>> <<set>>
    + PistasReservadas : IList<PistaReservada> <<get>> <<set>>
}
@enduml
