@startuml
class PistaReservada {
    + Id : int <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + Precio : decimal <<get>> <<set>>
    + Observaciones : string <<get>> <<set>>
    + IdPista : int <<get>> <<set>>
    + IdReserva : int <<get>> <<set>>
}
PistaReservada --> "Pista" Pista
PistaReservada --> "Reserva" Reserva
@enduml
