@startuml
class Reserva {
    + Reserva()
    + Id : int <<get>> <<set>>
    + NombreCliente : string <<get>> <<set>>
    + Apellidos : string <<get>> <<set>>
    + Dni : string <<get>> <<set>>
    + FechaReserva : DateTime <<get>> <<set>>
    + MetodoPago : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
}
@enduml
