@startuml
class TipoMaterial {
    + TipoMaterial()
    + TipoMaterial(idtipomaterial:string, nametipomaterial:string, materiales:IList<Material>)
    + IdTipoMaterial : string <<get>> <<set>>
    + NameTipoMaterial : string <<get>> <<set>>
    + Materiales : IList<Material> <<get>> <<set>>
    + <<override>> Equals(obj:object?) : bool
    + <<override>> GetHashCode() : int
}
@enduml
